### PR TITLE
CI: add circle-ci integration

### PR DESCRIPTION
**Pull request by andelf**
To enable auto deployment:

- Enable this project in https://circleci.com
- Under project settings
    - `SSH Permissions` tab: Add host private key, leaving hostname empty is ok
    -  `Environment Variables` tab:
        - `DEPLOY_HOST` variable, ip address is ok
        - `DEPLOY_USER`
        - `DEPLOY_PATH`: /home/xxxx/path/to/website/root

+Question:
will this repo always update its submodules to newest? or update manually(via script) to make website content version traceable. Each push master triggers deployment.

### CODE REVIEW

**Comment by andelf** [comment]
@xuechunL

**Comment by GregoryIan** [comment]
LGTM

**Comment by andelf** [comment]
sample page: https://circleci.com/gh/andelf/docs-interface/9

**Comment by gaohailang** [comment]
@andelf thx. 
I think we will use other submodules's webhook(when new commits) to notify new webiste's circleci to rebuild.

**Pull request merged**
